// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/S3_Pos0_Command.h"
#include "Commands/S3_Pos1_Command.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    armStick.reset(new frc::Joystick(0));
    
    s3_Pos1.reset(new frc::JoystickButton(armStick.get(), 1));
    s3_Pos1->WhenPressed(new S3_Pos1_Command());
    s3_Pos0.reset(new frc::JoystickButton(armStick.get(), 1));
    s3_Pos0->WhenPressed(new S3_Pos0_Command());

    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("S3_Pos1_Command", new S3_Pos1_Command());
    frc::SmartDashboard::PutData("S3_Pos0_Command", new S3_Pos0_Command());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    printf("OI Complete\n");
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getarmStick() {
   return armStick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
